services:
  postgres:
    container_name: hospital-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital
    ports:
      - 5432:5432

  redis:
    container_name: hospital-redis
    image: redis
    ports:
      - 6379:6379
